# Generated by Django 4.1.5 on 2023-03-01 18:46

import catsapps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catsapps", "0003_cat_behavor_cat_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="behavor",
            name="behavor",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="cat",
            name="behavor",
            field=models.CharField(max_length=30, verbose_name=catsapps.models.Behavor),
        ),
        migrations.AlterField(
            model_name="cat",
            name="color",
            field=models.CharField(max_length=30, verbose_name=catsapps.models.Color),
        ),
        migrations.AlterField(
            model_name="cat",
            name="kind",
            field=models.CharField(max_length=30, verbose_name=catsapps.models.Kind),
        ),
        migrations.AlterField(
            model_name="color",
            name="color",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="kind",
            name="kind",
            field=models.CharField(max_length=100),
        ),
    ]
