# Generated by Django 4.1.5 on 2023-05-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shoes", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="category",
            new_name="shoes_categ_name_3894dc_idx",
            old_name="shoes_catego_name_289c7e_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="shoes_produ_id_139638_idx",
            old_name="shoes_produc_id_f21274_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="shoes_produ_name_25c713_idx",
            old_name="shoes_produc_name_a2070e_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="shoes_produ_created_503438_idx",
            old_name="shoes_produc_created_ef211c_idx",
        ),
    ]
